### PR TITLE
Support for Field Kit controls in XIBs

### PR DESCRIPTION
**Pull request by jchaager**
This pull request adds an awakeFromNib method to each of the 3 widgets so that they can be created via Interface Builder with the correct type and still have them function when the NIB loads.  All of the initialization code that was in the init... method has been moved into a setupInstance method that is invoked both in the init method as well as in the awakeFromNib method.

### CODE REVIEW

**Comment by laugga** [comment]
@jchaager I like it. However I found 1 issue:

1. I get the following compilation error:

fieldkit/lib/FKTokenField/FKTokenField.m:101:13: No visible @interface for 'FKTextField' declares the selector 'setupInstance'

You must declare the method 'setupInstance' in the [private] class extension of FKTextField (declared in FKTextField_Internal.h). Then you also need to import it in the implementation file of FKTokenField (FKTokenField.m).

#import "FKTextField_Internal.h"

**Comment by laugga** [comment]
2. I also have suggestion regarding coding styling:

[ super setupInstance ] ;

should be without spaces, like:

[super setupInstance];

**Comment by jchaager** [comment]
@laugga I have corrected the compile error as you suggested and made the style changes  as well.

**Comment by laugga** [comment]
@jchaager One last thing, we should also call:
 
[super awakeFromNib];

Here's why:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/NSObject_UIKitAdditions/index.html#//apple_ref/occ/instm/NSObject/awakeFromNib

Thank you!

**Comment by jchaager** [comment]
Okay.  If I call [super awakeFromNib]; then I don’t need to call [super setupInstance] since the super class’s awakeFromNib method will handle that.  Much cleaner that way.

**Comment by jchaager** [comment]
There is an issue with the way the awakeFromNib chaining is working.

**Comment by jchaager** [comment]
Fixed the awakeFromNib issue.  Code is now working as expected.

**Comment by laugga** [comment]
@jchaager tested and it works. I'll merge. Thank you!

**Pull request merged**
